### ISSUE TITLE
Not working as desired

### ISSUE THREAD

**Issue by arjunnambiartc** [jalphonso/awx_haproxy#1]
I set this up just as per the instructions..My docker ps is as follows now:

[root@ansibleawx.ops awx_haproxy]# docker-compose up
Creating awxhaproxy_postgres_1  ... done
Creating awxhaproxy_rabbitmq_1  ... done
Creating awxhaproxy_memcached_1 ... done
Creating awxhaproxy_memcached_1 ...
Creating awxhaproxy_web_1       ... done
Creating awxhaproxy_rabbitmq_1  ...
Creating awxhaproxy_web_1       ...
Creating awxhaproxy_lb_1        ... error
Creating awxhaproxy_task_1      ...

ERROR: for awxhaproxy_lb_1  Cannot start service lb: driver failed programming external connectivity on endpoint awxhaproxy_lb_1 (c48522b09194271b5701e4511d75c39bb08d2d307ef60b66bc146e8037fc1b7a): Bind for 0.0.0.0:80 failed: port is alreaCreating awxhaproxy_task_1      ... done

ERROR: for lb  Cannot start service lb: driver failed programming external connectivity on endpoint awxhaproxy_lb_1 (c48522b09194271b5701e4511d75c39bb08d2d307ef60b66bc146e8037fc1b7a): Bind for 0.0.0.0:80 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

[root@ansibleawx.ops awx_haproxy]# docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED              STATUS                        PORTS                                NAMES
71ecd301904c        ansible/awx_task:latest   "/tini -- /bin/sh -c…"   47 seconds ago       Up 46 seconds                 8052/tcp                             awxhaproxy_task_1
5d6129c7bb26        ansible/awx_web:latest    "/tini -- /bin/sh -c…"   47 seconds ago       Up 47 seconds                 8052/tcp                             awxhaproxy_web_1
a471477f4a3f        postgres:9.6              "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)   5432/tcp                             awxhaproxy_postgres_1
019e477846f8        rabbitmq:3                "docker-entrypoint.s…"   About a minute ago   Up About a minute             4369/tcp, 5671-5672/tcp, 25672/tcp   awxhaproxy_rabbitmq_1
017abf227dda        memcached:alpine          "docker-entrypoint.s…"   About a minute ago   Up About a minute             11211/tcp                            awxhaproxy_memcached_1
fd042cef74fb        ansible/awx_task:latest   "/tini -- /bin/sh -c…"   3 hours ago          Up 3 hours                    8052/tcp                             awx_task
eaf3432b9aa8        ansible/awx_web:latest    "/tini -- /bin/sh -c…"   3 hours ago          Up 3 hours                    0.0.0.0:80->8052/tcp                 awx_web
c33654a05ecc        memcached:alpine          "docker-entrypoint.s…"   3 hours ago          Up 3 hours                    11211/tcp                            memcached
e3f90e5520dd        rabbitmq:3                "docker-entrypoint.s…"   3 hours ago          Up 3 hours                    4369/tcp, 5671-5672/tcp, 25672/tcp   rabbitmq
edbf36db18d4        postgres:9.6              "docker-entrypoint.s…"   3 hours ago          Up 3 hours                    5432/tcp                             postgres

However, it still accepts connections on port 80 and refuses connections on port 443 after this

**Comment by jalphonso** [comment]
Are you running other services on this server? It looks like port 80 is already in use by another process. Also, I noticed the directory you ran it from was awx_haproxy. I should probably add this to the readme but the docker-compose file names the containers based on the current directory (where you have the compose file). In the haproxy.cfg I expected the awx_web instance to be named awx_web_1 so either update the reference here: https://github.com/jalphonso/awx_haproxy/blob/b73886791a5abd3092a8ecd01b5c8a1c9a32bb6c/haproxy.cfg#L30 or create an awx directory and put your docker-compose.yml file in there.

**Comment by arjunnambiartc** [comment]
The inventory file inside my installer folder has the following settings:

> # Common Docker parameters
>postgres_data_dir=/tmp/pgdocker
>host_port=80

which is where the awx_web container runs as is evident from the **docker ps** command output:
>7e63ba67dd83        ansible/awx_web:latest    "/tini -- /bin/sh -c…"   22 seconds ago       Up 21 >seconds       0.0.0.0:80->8052/tcp                 awx_web

Do i have to do something different here ?

**Comment by jalphonso** [comment]
Yes. awx_web cannot be listening on port 80. If you use the supplied docker-compose.yml file and run docker-compose up it should resolve this. Sounds like you are still using the AWX install playbook. You would need to set use_docker_compose=true and modify the docker-compose.yml.j2 in order for this to work. Example here: https://github.com/jalphonso/awx/commit/7f3ba7ad2de68fa6efdcc9511b56a2e109133887#diff-f3aa76575824f0d4dbf826af29cfdb96

**Comment by arjunnambiartc** [comment]
@jalphonso ..thanks for your help on this..I edited the files inside the AWX install playbook and now get this error:

> 

TASK [local_docker : Start the containers] ***************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "errors": [], "module_stderr": "", "module_stdout": "", "msg": "Error starting project 500 Server Error: Internal Server Error (\"Get http://localhost:5000/v2/: dial tcp 127.0.0.1:5000: getsockopt: connection refused\")"}

**Comment by jalphonso** [comment]
right. My file is referencing images in my docker private registry. Use the public ones. I assume you already generated your PEM file and built your own haproxy image based on the README instructions. Whatever you named your image needs to referenced in the docker-compose.yml file. Example with public images here: https://github.com/jalphonso/awx_task/blob/master/docker-compose.yml
